### ISSUE TITLE
Consider replacing kitsu.js with kitsu

### ISSUE THREAD

**Issue by wopian** [Mitorisia/Komugari#8]
[kitsu.js](https://yarnpkg.com/en/package/kitsu.js) is deprecated in favour of the more feature complete [kitsu](https://yarnpkg.com/en/package/kitsu) package that is fully JSON-API compliant.

Based on [your current usage], search implementation would be something like:

```js
const Kitsu = require('kitsu')
const kitsu = new Kitsu()

kitsu.fetch('anime', {
  filter: { 
    text: aq().quoteanime
  },
  // Reduce the response to only fields you require (not required, but great to do)
  fields: {
    anime: 'titles,subtype,posterImage'
  }
}).then({ data } => {
  ...
  .setAuthor(`${data.titles.en} | ${data.subtype}`, data.posterImage.original)
  ...
})
```

[your current usage]:https://github.com/Mitorisia/Komugari/blob/2e2330efc0f5f29d542748bca90fd8e87c74288e/commands/anime/anime.js#L29

**Comment by Mitorisia** [comment]
👌👌 getting right to it
